"""
ListClass.py

A class that contains all of the relevant lists for Neurosynth_SNA.py
"""

class ListClass:
	def __init__(self):

		self.sub_Beam_concepts= ["face", "novelty", "episodic", "retrieval", "semantic", "word", "emotion", "sequence", "category", "memory", "encoding", "load", "social", "cognition",
		"motor", "learning", "representation", "executive", "control", "object", "recognition", "inhibition", "target", "top-down", "attention", "selection", "vision",
		"auditory", "detection", "motion", "spatial", "information", "perception", "shape", "speech", "sensory", "prediction", "error", "risk", "reward", "future", "anticipation",
		"working memory", "verbal", "action", "observation", "movement", "priming", "repetition", "suppression"]

		self.sub_Beam_brain = ["intraparietal sulcus", "PSTS", "cingulate cortex", "temporal sulcus", "precuneus", "STS", "PCC", "frontal", "premotor cortex", "STG", "PCC", "mPFC", 
		"DmPFC", "DlPFC", "OFC", "parietal cortex", "temporal cortex", "PFC", "thalamus", "ACC", "Pre-SMA", "PPC", "MTL", "amygdala", "anterior insula", "insula", "hippocampus", 
		"fusiform", "FFA", "putamen", "caudate", "S2", "S1", "M1", "cingulate", "SMA", "cerebellum", "somatosensory cortex", "basal ganglia", "LIFG", "RIFG", "IFG", "IPL", "MTA",
		"V5", "extrastriate", "visual cortex", "V1", "V2", "V3"]

		self.sub_Beam_concept_and_brain = ["decision making", "frontoparietal cortex", "occipital cortex", "fusiform", "FEF", "emotion", "sensitivity", "fear", "ACC", "attention", "cognition", "amygdala", "FFA", 
		"prediction", "OFC", "observation", "control", "brainstem", "executive", "PFC", "parietal cortex", "novelty", "retrieval", "memory", "hippocampus", "selection", "vision", "information", "active", 
		"top-down", "cerebellum", "extrastriate", "learning", "encoding", "MTL", "parahippocampus", "visual cortex", "object", "representation", "V1", "somatosensory", "S2", 
		"sensorimotor", "language", "frontal", "semantic", "LIFG", "M1", "motor", "premortor cortex", "V5", "motion", "MTA"]

		self.thesaurus = [('ability', 'abilities', 'ability|abilities'),
							('action', 'actions', 'action|actions'),
							('adolescence', 'adolescents', 'adolescence|adolescents'),
							('affect', 'affective', 'affect|affective'),
							('age', 'agerelated', 'age|agerelated'),
							('ambiguous', 'ambiguity', 'ambiguous|ambiguity'),
							('anger', 'angry', 'anger|angry')
							('animal', 'animals', 'animal|animals'),
							('anticipation', 'anticipatory', 'anticipation|anticipatory'),
							('association', 'associations', 'associative', 'association|associations|associative'),
							('attend', 'attended', 'attend|attended'),
							('attention', 'attentional', 'attention|attentional'),
							('autism', 'autistic', 'autism|autistic'),
							('card', 'cards', 'card|cards'),
							('child', 'childhood', 'children', 'child|childhood|children'),
							('choice', 'choices', 'choice|choices'),
							('color', 'colors', 'colour', 'color|colors|colour'),
							('condtioning', 'conditioned', 'conditioning|condtioned'),
							('congruent', 'congruency', 'congruent|congruency'),
							('cue', 'cued', 'cueing', 'cues', 'cue|cued|cueing|cues'),
							('decision', 'decisionmaking', 'decisions', 'decision|decisions|decisionmaking'),
							('demand', 'demands', 'demand|demands'),
							('depression', 'depressed', 'depressive', 'depression|depressed|depressive'),
							('development', 'developmental', 'development|developmental'),
							('digit', 'digits', 'digit|digits'),
							('distractor', 'distractors', 'distractor|distractors'),
							('dopamine', 'dopaminergic', 'dopamine|dopaminergic'),
							('drug', 'drugs', 'drug|drugs'),
							('emotion', 'emotionally', 'emotions', 'emotion|emotionally|emotions'),
							('empathy', 'empathic', 'empathy|empathic'),
							('encoded', 'encoding', 'encoded|encoding'),
							('engaged', 'engagement', 'engaged|engagement'),
							('error', 'errorrelated', 'errors', 'error|errorrelated|errors'),
							('expectancy', 'expectation', 'expectancy|expectation'),
							('experience', 'experiences', 'experience|experiences'),
							('expression', 'expressions', 'expression|expressions'),
							('eye', 'eyes', 'eye|eyes'),
							('face', 'faces', 'facial', 'face|faces|facial'),
							('familiar', 'familiarity', 'familiar|familiarity'),
							('female', 'females', 'female|females'),
							('finger', 'fingers', 'finger|fingers'),
							('gesture', 'gestures', 'gesture|gestures'),
							('hand', 'hands', 'hand|hands'),
							('image', 'images', 'image|images'),
							('imagine', 'imagined', 'imagine|imagined'),
							('inhibition', 'inhibitory', 'inhibition|inhibitory'),
							('intention', 'intentions', 'intentional', 'intention|intentions|intentional'),
							('judgment', 'judgements', 'judgment|judgements'),
							('language', 'languages', 'language|languages'),
							('learning', 'learned', 'learning|learned'),
							('letter', 'letters', 'letter|letters'),
							('loss', 'losses', 'loss|losses'),
							('male', 'males', 'male|males'),
							('mask', 'masked', 'masking', 'mask|masked|masking'),
							('memory', 'memories', 'memory|memories'), 
							('money', 'monetary', 'money|monetary'),
							('muscle', 'muscles', 'muscle|muscles'),
							('music', 'musical', 'music|musical'),
							('name', 'names', 'naming', 'name|names|naming'),
							('negative', 'negatively', 'negative|negatively'),
							('noun', 'nouns', 'noun|nouns'),
							('novel', 'novelty', 'novel|novelty'),
							('number', 'numbers', 'number|numbers'),
							('object', 'objects', 'object|objects'),
							('outcome', 'outcomes', 'outcome|outcomes'),
							('pain', 'painful', 'painrelated', 'pain|painful|painrelated'),
							('pair', 'paired', 'pairs', 'pair|paired|pairs'),
							('perception', 'perceptual', 'perception|perceptual'),
							('person', 'persons', 'person|persons'),
							('phonology', 'phonological', 'phonology|phonological'),
							('picture', 'pictures', 'picture|pictures'),
							('preparation', 'preparatory', 'preparation|preparatory'),
							('prime', 'priming', 'prime|priming'),
							('probability', 'probablities', 'probabilistic', 'probability|probablities|probabilistic'),
							('probe', 'probes', 'probe|probes'),
							('prosody', 'prosodic', 'prosody|prosodic'),
							('pseudoword', 'pseudowords', 'pseudoword|pseudowords'),
							('rating', 'ratings', 'rating|ratings'),
							('read', 'reading', 'read|reading'),
							('recall', 'recollection', 'recall|recollection'),
							('remember, remembered', 'remember|remembered'),
							('repetition', 'repetitions', 'repetition|repetitions'),
							('rest', 'restingstate', 'rest|restingstate'),
							('retrieval', 'retrieved', 'retrieval|retrieved'),
							('reward', 'rewards', 'reward|rewards'),
							('rule', 'rules', 'rule|rules'),
							('saccadic', 'saccade', 'saccades', 'saccadic|saccade|saccades'),
							('salience', 'salient', 'salience|salient'),
							('scene', 'scenes', 'scene|scenes'),
							('schizophrenia', 'schizophrenic', 'schizophrenia|schizophrenic'),
							('semantic', 'semantically', 'semantic|semantically'),
							('sentence', 'sentences', 'sentence|sentences'),
							('sequence', 'sequences', 'sequence|sequences'),
							('sex', 'sexual', 'sex|sexual'),
							('shape', 'shapes', 'shape|shapes'),
							('shifting', 'shifts', 'shifting|shifts'),
							('sound', 'sounds', 'sound|sounds'),
							('spatial', 'spatially', 'spatial|spatially'),
							('story', 'stories', 'story|stories'),
							('strategy', 'strategies', 'strategy|strategies'),
							('switch', 'switching', 'switch|switching'),
							('target', 'targets', 'target|targets'),
							('taskrelated', 'taskrelevant', 'taskrelated|taskrelevant'),
							('thinking', 'thought', 'thoughts', 'thinking|thought|thoughts'),
							('tom', 'mentalizing', 'tom|mentalizing'),
							('training', 'trained', 'training|trained'),
							('trait', 'traits', 'trait|traits'),
							('unpleasant', 'unpleasantness', 'unpleasant|unpleasantness'),
							('verb', 'verbal', 'verb|verbal'),
							('violation', 'violations', 'violation|violations'),
							('visual', 'visually', 'visual|visually'),
							('wm', 'working', 'wm|working'),
							('word', 'words', 'word|words')]

