
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '35!\xc7AD\x1b\xd2*\xe7F\x0f\xbfK\xad\xe9'
    
_lr_action_items = {'AND':([2,3,4,10,11,12,13,14,15,16,],[5,-6,5,-7,5,-5,-8,-4,5,5,]),'LPAR':([0,1,5,8,9,],[1,1,1,1,1,]),'FLOAT':([6,7,],[13,13,]),'FEATURE':([0,1,5,8,9,],[3,3,3,3,3,]),'RPAR':([3,4,10,11,12,13,14,15,16,],[-6,10,-7,-2,-5,-8,-4,-1,-3,]),'LT':([2,3,4,10,11,12,13,14,15,16,],[7,-6,7,-7,7,-5,-8,-4,7,7,]),'RT':([2,3,4,10,11,12,13,14,15,16,],[6,-6,6,-7,6,-5,-8,-4,6,6,]),'ANDNOT':([2,3,4,10,11,12,13,14,15,16,],[8,-6,8,-7,8,-5,-8,-4,8,8,]),'OR':([2,3,4,10,11,12,13,14,15,16,],[9,-6,9,-7,9,-5,-8,-4,9,9,]),'$end':([2,3,10,11,12,13,14,15,16,],[0,-6,-7,-2,-5,-8,-4,-1,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'freq':([6,7,],[12,14,]),'list':([0,1,5,8,9,],[2,4,11,15,16,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> list","S'",1,None,None,None),
  ('list -> list ANDNOT list','list',3,'p_list_andnot','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',65),
  ('list -> list AND list','list',3,'p_list_and','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',69),
  ('list -> list OR list','list',3,'p_list_or','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',73),
  ('list -> list LT freq','list',3,'p_list_lt','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',78),
  ('list -> list RT freq','list',3,'p_list_rt','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',82),
  ('list -> FEATURE','list',1,'p_list_feature','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',86),
  ('list -> LPAR list RPAR','list',3,'p_list_expr','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',90),
  ('freq -> FLOAT','freq',1,'p_freq_float','M:KBE.01\\Analysis\\Neurosynth\\neurosynthgit\\neurosynth\\base\\lexparser.py',94),
]
